module.exports=
{
    products:[
        {
            _id:'1',
            name : 'full zip running',
            category:'shirts' ,
            image:'/images/product-1.jpg',
            price: 60,
            brand : 'nike',
            numReviews:10,
            countInstock:6,
        },
        {
            _id:'2',
            name : 'full zip running',
            category:'shirts' ,
            image:'/images/product-1.jpg',
            price: 90,
            brand : 'nike',
            numReviews:10,
            countInstock:6,
        },
        {
            _id:'3',
            name : 'full zip running',
            category:'shirts' ,
            image:'/images/product-1.jpg',
            price: 90,
            brand : 'nike',
            numReviews:10,
            countInstock:6,
        },
        {
            _id:'4',
            name : 'full zip running',
            category:'shirts' ,
            image:'/images/product-1.jpg',
            price: 90,
            brand : 'nike',
            numReviews:10,
            countInstock:6,
        },
        {
            _id:'5',
            name : 'full zip running',
            category:'shirts' ,
            image:'/images/product-1.jpg',
            price: 90,
            brand : 'nike',
            numReviews:10,
            countInstock:6,
        },
    ]
}